name: Destroy EKS

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  destroy-eks-cluster:
    name: Destroy EKS cluster using Terraform templates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Kubeconfig for EKS
        run: aws eks update-kubeconfig --region us-east-1 --name rajuru
        continue-on-error: true

      - name: Set up Terraform-CLI
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Terraform destroy
        run: |

          echo "" RUNNING TERRAFORM destroy ""       

          terraform init   

          terraform destroy -auto-approve